<?php
namespace Tests\Feature;
use App\Models\Conseil; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Tests\TestCase;
class ConseilTest extends TestCase { use RefreshDatabase;
 private function admin(): User { return User::factory()->create(['role'=>'admin']); }
 public function test_admin_crud_and_sync_work_without_duplicates(): void { $admin=$this->admin(); $e=$admin->equipements()->create(['nom'=>'Réfrigérateur','type'=>'Électroménager','sensible_chaleur'=>true,'sensible_coupure'=>true]); $this->actingAs($admin)->get('/conseils')->assertOk(); $this->actingAs($admin)->post('/conseils',['titre'=>'Fermer les portes','description'=>'Limiter la perte de froid.','categorie'=>'Coupure électrique','niveau'=>'Important','actif'=>true,'equipements'=>[$e->id,$e->id]])->assertRedirect('/conseils'); $c=Conseil::firstOrFail(); $this->assertSame(1,$c->equipements()->count()); $this->actingAs($admin)->put(route('conseils.update',$c),['titre'=>'Fermer les portes rapidement','description'=>'Limiter la perte de froid.','categorie'=>'Coupure électrique','niveau'=>'Urgent','actif'=>true,'equipements'=>[$e->id]])->assertRedirect(route('conseils.show',$c)); $this->actingAs($admin)->delete(route('conseils.destroy',$c))->assertRedirect('/conseils'); $this->assertDatabaseMissing('conseils',['id'=>$c->id]); }
 public function test_habitant_cannot_manage_conseils_but_sees_only_own_active_conseils(): void { $h=User::factory()->create(['role'=>'habitant']); $other=User::factory()->create(['role'=>'habitant']); $own=$h->equipements()->create(['nom'=>'PC','type'=>'Informatique','sensible_chaleur'=>true,'sensible_coupure'=>false]); $foreign=$other->equipements()->create(['nom'=>'Pompe','type'=>'Médical','sensible_chaleur'=>true,'sensible_coupure'=>true]); $mine=Conseil::create(['titre'=>'Aérer le PC','description'=>'Éviter la surchauffe.','categorie'=>'Chaleur','niveau'=>'Important','actif'=>true]); $hidden=Conseil::create(['titre'=>'Conseil privé','description'=>'Autre équipement.','categorie'=>'Sécurité','niveau'=>'Information','actif'=>true]); $mine->equipements()->attach($own); $hidden->equipements()->attach($foreign); $this->actingAs($h)->get('/conseils')->assertForbidden(); $this->actingAs($h)->get('/conseils/create')->assertForbidden(); $this->actingAs($h)->put(route('conseils.update',$mine),[])->assertForbidden(); $this->actingAs($h)->delete(route('conseils.destroy',$mine))->assertForbidden(); $this->actingAs($h)->get('/mes-conseils')->assertOk()->assertSee('Aérer le PC')->assertDontSee('Conseil privé'); $this->post('/logout')->assertRedirect('/login'); $this->get('/mes-conseils')->assertRedirect('/login'); }
 public function test_equipement_show_displays_its_conseils(): void { $u=User::factory()->create(); $e=$u->equipements()->create(['nom'=>'Climatiseur','type'=>'Climatisation','sensible_chaleur'=>true,'sensible_coupure'=>false]); $c=Conseil::create(['titre'=>'Nettoyer le filtre','description'=>'Améliorez le rendement.','categorie'=>'Protection appareil','niveau'=>'Information','actif'=>true]); $c->equipements()->attach($e); $this->actingAs($u)->get(route('equipements.show',$e))->assertOk()->assertSee('Conseils associés')->assertSee('Nettoyer le filtre'); }
}
