<?php
namespace Tests\Feature;
use App\Models\Quartier; use App\Models\User; use Illuminate\Foundation\Testing\RefreshDatabase; use Illuminate\Support\Facades\Http; use Tests\TestCase;
class MeteoTest extends TestCase { use RefreshDatabase;
 public function test_admin_can_create_quartier_and_habitant_cannot():void{$admin=User::factory()->create(['role'=>'admin']);$payload=['nom'=>'Bardo','ville'=>'Tunis','code_postal'=>'2000','latitude'=>36.809,'longitude'=>10.140,'actif'=>true];$this->actingAs($admin)->post('/admin/quartiers',$payload)->assertRedirect('/admin/quartiers');$this->assertDatabaseHas('quartiers',['nom'=>'Bardo']);$this->actingAs(User::factory()->create(['role'=>'habitant']))->get('/admin/quartiers')->assertForbidden();}
 public function test_habitant_sees_weather_for_own_quartier():void{$q=Quartier::create(['nom'=>'Bardo','ville'=>'Tunis','latitude'=>36.809,'longitude'=>10.140,'actif'=>true]);$u=User::factory()->create(['quartier_id'=>$q->id]);Http::fake(['api.open-meteo.com/*'=>Http::response(['current'=>['temperature_2m'=>41],'daily'=>['temperature_2m_max'=>[43],'temperature_2m_min'=>[29]]])]);$this->actingAs($u)->get('/alertes-meteo')->assertOk()->assertSee('41')->assertSee('Alerte');}
 public function test_user_without_quartier_sees_selection_message():void{$u=User::factory()->create();$this->actingAs($u)->get('/alertes-meteo')->assertOk()->assertSee('Veuillez sélectionner votre quartier');}
 public function test_admin_generates_one_open_meteo_alert():void{$q=Quartier::create(['nom'=>'Bardo','ville'=>'Tunis','latitude'=>36.809,'longitude'=>10.140,'actif'=>true]);$u=User::factory()->create(['role'=>'admin']);Http::fake(['api.open-meteo.com/*'=>Http::response(['current'=>['temperature_2m'=>41],'daily'=>['temperature_2m_max'=>[43],'temperature_2m_min'=>[29]]])]);$this->actingAs($u)->post(route('admin.quartiers.generate',$q))->assertSessionHas('success');$this->assertDatabaseHas('alerte_meteos',['quartier_id'=>$q->id,'temperature'=>41,'niveau'=>'Alerte','source'=>'open-meteo']);}
}
