@extends('layouts.user')

@section('title', $equipement->nom . ' - HeatAlert')

@section('content')
    <div class="page-header d-print-none"><div class="row align-items-center"><div class="col"><div class="page-pretitle">Mes équipements</div><h2 class="page-title">{{ $equipement->nom }}</h2></div><div class="col-auto ms-auto d-print-none"><div class="btn-list"><a href="{{ route('equipements.edit', $equipement) }}" class="btn btn-primary">Modifier</a><a href="{{ route('equipements.index') }}" class="btn btn-outline-secondary">Retour à la liste</a></div></div></div></div>
    @if (session('success'))<div class="alert alert-success" role="alert">{{ session('success') }}</div>@endif
    <div class="row row-cards"><div class="col-lg-8"><div class="card"><div class="card-header"><h3 class="card-title">Fiche équipement</h3></div><div class="card-body"><dl class="row"><dt class="col-5">Nom</dt><dd class="col-7">{{ $equipement->nom }}</dd><dt class="col-5">Type</dt><dd class="col-7">{{ $equipement->type }}</dd><dt class="col-5">Marque</dt><dd class="col-7">{{ $equipement->marque ?: 'Non renseignée' }}</dd><dt class="col-5">Sensible à la chaleur</dt><dd class="col-7"><span class="badge {{ $equipement->sensible_chaleur ? 'bg-orange-lt text-orange' : 'bg-secondary-lt text-secondary' }}">{{ $equipement->sensible_chaleur ? 'Oui' : 'Non' }}</span></dd><dt class="col-5">Sensible aux coupures</dt><dd class="col-7"><span class="badge {{ $equipement->sensible_coupure ? 'bg-red-lt text-red' : 'bg-secondary-lt text-secondary' }}">{{ $equipement->sensible_coupure ? 'Oui' : 'Non' }}</span></dd><dt class="col-5">Date d'ajout</dt><dd class="col-7">{{ $equipement->created_at->format('d/m/Y') }}</dd><dt class="col-5">Description</dt><dd class="col-7">{{ $equipement->description ?: 'Aucune description.' }}</dd></dl></div><div class="card-footer"><form action="{{ route('equipements.destroy', $equipement) }}" method="POST" onsubmit="return confirm('Supprimer définitivement cet équipement ?')">@csrf @method('DELETE')<button class="btn btn-danger" type="submit">Supprimer l'équipement</button></form></div></div><div class="card mt-3"><div class="card-header"><h3 class="card-title">Conseils associés</h3></div><div class="list-group list-group-flush">@forelse($equipement->conseils as $conseil)<div class="list-group-item"><strong>{{ $conseil->titre }}</strong> <span class="badge bg-blue-lt">{{ $conseil->categorie }}</span> <span class="badge bg-orange-lt text-orange">{{ $conseil->niveau }}</span><div class="text-secondary mt-1">{{ $conseil->description }}</div></div>@empty<div class="list-group-item text-secondary">Aucun conseil associé à cet équipement.</div>@endforelse</div></div></div></div>
@endsection
