@extends('layouts.user')

@section('title', $pointFraicheur->nom)

@section('content')
    <div class="page-header"><div class="row align-items-center"><div class="col"><div class="page-pretitle">Point de fraîcheur</div><h2 class="page-title">{{ $pointFraicheur->nom }}</h2><div class="text-secondary">{{ $pointFraicheur->type }} · {{ $pointFraicheur->quartier?->nom }}</div></div><div class="col-auto mt-3 mt-sm-0"><a class="btn btn-outline-primary" href="{{ route('points-fraicheur.index') }}">Retour à la liste</a></div></div></div>

    <div class="row row-cards">
        <div class="col-lg-8">
            <div class="card"><div class="card-header"><h3 class="card-title">Informations pratiques</h3></div><div class="card-body"><p class="text-secondary">{{ $pointFraicheur->description ?: 'Aucune description complémentaire n’est disponible.' }}</p><div class="row row-cards"><div class="col-md-6"><div class="text-secondary small">Adresse</div><div class="fw-semibold">{{ $pointFraicheur->adresse }}</div></div><div class="col-md-6"><div class="text-secondary small">Horaires</div><div class="fw-semibold">{{ $pointFraicheur->horaires ?: 'Non renseignés' }}</div></div><div class="col-md-6"><div class="text-secondary small">Téléphone</div><div class="fw-semibold">{{ $pointFraicheur->telephone ?: 'Non renseigné' }}</div></div><div class="col-md-6"><div class="text-secondary small">Origine</div><div class="fw-semibold">{{ $pointFraicheur->source === 'geoapify' ? 'Lieu découvert via Geoapify' : 'Ajouté par l’administration' }}</div></div></div><div class="mt-4 d-flex flex-wrap gap-2">@if($pointFraicheur->climatise)<span class="badge bg-blue-lt text-blue">Climatisé</span>@endif @if($pointFraicheur->eau_disponible)<span class="badge bg-cyan-lt text-cyan">Eau disponible</span>@endif @if($pointFraicheur->accessible_pmr)<span class="badge bg-green-lt text-green">Accessible PMR</span>@endif @if($pointFraicheur->source === 'geoapify')<span class="badge bg-indigo-lt text-indigo">Geoapify API</span>@endif</div></div></div>
            <div class="card mt-3"><div class="card-header"><h3 class="card-title">Localisation <span class="badge bg-blue-lt text-blue ms-1">OpenStreetMap</span></h3></div><div class="card-body"><div class="small text-secondary mb-3">Latitude {{ $pointFraicheur->latitude }} · Longitude {{ $pointFraicheur->longitude }}</div><div id="point-fraicheur-map" class="rounded border" style="height: 340px;"></div></div></div>
            <div class="card mt-3"><div class="card-header"><h3 class="card-title">Avis des habitants</h3></div><div class="list-group list-group-flush">@forelse($avisPublies as $avis)<div class="list-group-item"><div class="d-flex justify-content-between gap-3"><strong>{{ $avis->user?->name ?? 'Habitant' }}</strong><span class="badge bg-yellow-lt text-yellow">{{ $avis->note }} / 5</span></div>@if($avis->commentaire)<div class="mt-2">{{ $avis->commentaire }}</div>@endif<div class="small text-secondary mt-2">{{ $avis->created_at->format('d/m/Y') }}</div></div>@empty<div class="list-group-item text-secondary">Aucun avis publié pour le moment.</div>@endforelse</div></div>
        </div>
        <div class="col-lg-4">
            <div class="card"><div class="card-header"><h3 class="card-title">Évaluation</h3></div><div class="card-body"><div class="h1 mb-1">{{ $pointFraicheur->note_moyenne ? number_format($pointFraicheur->note_moyenne, 1, ',', ' ') . ' / 5' : '—' }}</div><div class="text-secondary">{{ $pointFraicheur->avis_publies_count }} avis publié{{ $pointFraicheur->avis_publies_count > 1 ? 's' : '' }}</div></div></div>
            <div class="card mt-3"><div class="card-header"><h3 class="card-title">{{ $monAvis ? 'Modifier mon avis' : 'Ajouter un avis' }}</h3></div><div class="card-body">@if($monAvis)<div class="alert alert-info">Statut actuel : {{ str_replace('_', ' ', ucfirst($monAvis->statut)) }}. Toute modification repasse en attente.</div>@endif<form method="POST" action="{{ $monAvis ? route('points-fraicheur.avis.update', [$pointFraicheur, $monAvis]) : route('points-fraicheur.avis.store', $pointFraicheur) }}">@csrf @if($monAvis) @method('PUT') @endif<label class="form-label">Note</label><select class="form-select" name="note" required>@for($note = 1; $note <= 5; $note++)<option value="{{ $note }}" @selected(old('note', $monAvis?->note) == $note)>{{ $note }} / 5</option>@endfor</select><label class="form-label mt-3">Commentaire <span class="text-secondary">(facultatif)</span></label><textarea class="form-control" name="commentaire" rows="4" maxlength="1000">{{ old('commentaire', $monAvis?->commentaire) }}</textarea><button class="btn btn-primary w-100 mt-3">{{ $monAvis ? 'Mettre à jour mon avis' : 'Envoyer mon avis' }}</button></form>@if($monAvis)<form method="POST" action="{{ route('points-fraicheur.avis.destroy', [$pointFraicheur, $monAvis]) }}" class="mt-2">@csrf @method('DELETE')<button class="btn btn-outline-danger w-100">Supprimer mon avis</button></form>@endif</div></div>
        </div>
    </div>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css">
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"></script>
    <script>
        const pointMap = L.map('point-fraicheur-map').setView([{{ $pointFraicheur->latitude }}, {{ $pointFraicheur->longitude }}], 15);
        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { attribution: '© OpenStreetMap' }).addTo(pointMap);
        L.marker([{{ $pointFraicheur->latitude }}, {{ $pointFraicheur->longitude }}]).addTo(pointMap).bindPopup(@json($pointFraicheur->nom));
    </script>
@endsection
